project:
  type: website

website:
  title: "שאילתות מהחיים"
  description: 'שאלות SQL מהיום-יום של אנליסט'
  navbar:
    right:
      - website.qmd
      - about.qmd
      - icon: github
        href: https://github.com/AmitLevinson/sql-website

format:
  html:
    theme: cosmo
    css: styles.css
    toc-depth: 3

editor: source

