project:
  type: website

title-meta: "שאילתות מהחיים"
description-meta: "תרגילי SQL משגרת העבודה של אנליסט"

website:
  site-url: https://sql.amitgrinson.com
  image: static/img/banner.png
  title: "שאילתות מהחיים"
  favicon: static/img/favicon.png
  description: "תרגילי SQL משגרת העבודה של אנליסט"
  page-navigation: true
  navbar:
    right:
      - website.qmd
      - about.qmd
      - icon: github
        href: https://github.com/AmitLevinson/sql-website
        
  twitter-card:
    card-style: summary
    creator: '@Amit_Levinson'
  open-graph:
    locale: he_IL
  cookie-consent:
    palette: light
  google-analytics:
    tracking-id: "G-YRDSPV195D"

format:
  html:
    theme: cosmo
    css: styles.css
    toc-depth: 3

editor: source

