project:
  type: website

website:
  site-url: https://sql.amitgrinson.com
  title: "שאילתות מהחיים"
  description: "תרגילי SQL משגרת העבודה של אנליסט"
  favicon: static/img/favicon.png
  navbar:
    right:
      - website.qmd
      - about.qmd
      - icon: github
        href: https://github.com/AmitLevinson/sql-website
  twitter-card:
    title: "שאילתות מהחיים"
    description: "תרגילי SQL משגרת העבודה של אנליסט"
    card-style: summary
    creator: '@Amit_Levinson'
  open-graph:
    title: "שאילתות מהחיים"
    description: "תרגילי SQL משגרת העבודה של אנליסט"

format:
  html:
    theme: cosmo
    css: styles.css
    toc-depth: 3

editor: source

