---
title: "אודות"
about:
  template: jolla
  links:
    - icon: twitter
      text: Twitter
      href: https://twitter.com/Amit_Levinson
    - icon: linkedin
      text: LinkedIn
      href: https://github.com/AmitLevinson
    - icon: github
      text: Github
      href: https://github.com
    - icon: website
      text: Website
      href: https://www.amitgrinson.com/
---

היי!

ברוכים הבאים לאתר שאילתות מהחיים. בבלוג/אוסף של שאלות אני מרכז מקרים מעניינים שיצא לי להתקל בהם במסגרת העבודה. לרוב זה יהיה משהו שפתרתי ואחשוב לעצמי "מגניב! בא לי שעוד אנשים יתנסו בזה" ואעלה את השאלה לפה כדי שתוכלו לנסות לפתור לבד, ולהשוות לפתרון שלי. כמובן כל הדאטה עובר איזשהי אנונימיזציה כך שלא יהיו פרטים מזהים.

לצערי, המון מעבודת האנליסט לא קיים בבלוג הזה, וזה שאילת השאלות האנליטיות שיביאו אותנו לכתוב את הקוד שיתן לנו את הדאטה שאנחנו צריכים. עם זאת, אני מקווה שהאתגרים הללו יוכלו לעזור לכם לתרגל בעצמכם ובכך להתכונן למשרה הראשונה/הבאה. כמו כן, אני גם מקווה שזה יראה לכם במה יוצא לי להיתקל בעבודה. חלק מהשאלות יהיו לכם קלות, חלק אולי קשות. מקווה כי מכולם תלמדו!

מוזמנים להירשם לניוזלטר ולקבל תזכורת כשיוצאת שאלה חדשה!

זהו, אם בא לכם ללמוד יותר עלי, מוזמנים להגיד שלום באחד מהקישורים מטה =>