DROP TABLE IF EXISTS ITEMS_Q6;


CREATE TABLE items_q6
    ([category] varchar(6), [amount] int)
;
    
INSERT INTO items_q6
    ([category], [amount])
VALUES
    ('Chairs', 12),
    ('Chairs', 10),
    ('Chairs', 10),
    ('Chairs', 44),
    ('Chairs', 93),
    ('Chairs', 93),
    ('Chairs', 32),
    ('Chairs', 99),
    ('Chairs', 95),
    ('Chairs', 98),
    ('Chairs', 85),
    ('Chairs', 1),
    ('Chairs', 39),
    ('Chairs', 95),
    ('Chairs', 91),
    ('Chairs', 15),
    ('Chairs', 38),
    ('Chairs', 47),
    ('Chairs', 31),
    ('Chairs', 20),
    ('Tables', 80),
    ('Tables', 602),
    ('Tables', 913),
    ('Tables', 694),
    ('Tables', 241),
    ('Tables', 981),
    ('Tables', 477),
    ('Tables', 187),
    ('Tables', 111),
    ('Tables', 603),
    ('Tables', 73),
    ('Tables', 47),
    ('Tables', 74),
    ('Tables', 37),
    ('Tables', 691),
    ('Tables', 93),
    ('Tables', 487),
    ('Tables', 873),
    ('Tables', 775),
    ('Tables', 4),
    ('Sofas', 146),
    ('Sofas', 431),
    ('Sofas', 330),
    ('Sofas', 161),
    ('Sofas', 308),
    ('Sofas', 437),
    ('Sofas', 97),
    ('Sofas', 55),
    ('Sofas', 383),
    ('Sofas', 422),
    ('Sofas', 127),
    ('Sofas', 331),
    ('Sofas', 213),
    ('Sofas', 29),
    ('Sofas', 260),
    ('Sofas', 244),
    ('Sofas', 398),
    ('Sofas', 497),
    ('Sofas', 276),
    ('Sofas', 397),
    ('Plates', 50),
    ('Plates', 6),
    ('Plates', 16),
    ('Plates', 29),
    ('Plates', 2),
    ('Plates', 6),
    ('Plates', 9),
    ('Plates', 20),
    ('Plates', 3),
    ('Plates', 48),
    ('Plates', 23),
    ('Plates', 27),
    ('Plates', 46),
    ('Plates', 18),
    ('Plates', 5),
    ('Plates', 12),
    ('Plates', 9),
    ('Plates', 15),
    ('Plates', 12),
    ('Plates', 14),
    ('Cups', 2),
    ('Cups', 10),
    ('Cups', 6),
    ('Cups', 4),
    ('Cups', 2),
    ('Cups', 4),
    ('Cups', 4),
    ('Cups', 5),
    ('Cups', 10),
    ('Cups', 4),
    ('Cups', 3),
    ('Cups', 6),
    ('Cups', 4),
    ('Cups', 6),
    ('Cups', 2),
    ('Cups', 4),
    ('Cups', 2),
    ('Cups', 9),
    ('Cups', 7),
    ('Cups', 1)
;

